services:
  db:
    image: 'postgres'
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin1234'
  server:
    build: .
    ports:
      - '4000:4000'
    environment:
      PORT: 4000
      DB_HOST: 'db'
      DB_PORT: 5432
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'admin1234'
      DB_NAME: 'postgres'
