services:
  db:
    image: 'postgres'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin1234'
  test:
    build:
      context: .
      dockerfile: 'Dockerfile-test'
    depends_on:
      - 'db'
    environment:
      PORT: 4000
      DB_HOST: 'db'
      DB_PORT: 5432
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'admin1234'
      DB_NAME: 'postgres'
